; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    ; Pin SimpleFOC to 2.3.2 to match current ESP32 framework
    askuric/Simple FOC @ 2.3.2
    rfetick/MPU6050_light
    tomstewart89/BasicLinearAlgebra @ ^5.1.0
    